# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SHShortVideoExmaple' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SHShortVideoExmaple

  target 'SHShortVideoExmapleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SHShortVideoExmapleUITests' do
    # Pods for testing
  end
  
  pod 'SHExtension/UIView'

end
